# Pages after is_section = true is indented

[[pages]]
path = "main.py"
name = "main"
icon = ':classical_building:'
is_section = true

[[pages]]
name = "My Page"
icon = ':information_desk_person:'
is_section = true

[[pages]]
path = "pages/info.py"
name = "info"

[[pages]]
path = "pages/performance.py"
name = "Performance"

[[pages]]
path = "pages/admin.py"
name = "Admin"

[[pages]]
name = "Math Drill"
icon = ':books:'
is_section = true

[[pages]]
path = "pages/menu.py"
name = "Menu"

[[pages]]
path = "pages/practice.py"
name = "Question"

[[pages]]
path = "pages/graded.py"
name = "Graded result"

[[pages]]
path = "pages/chatbot.py"
name = "Chat with AI"
icon = ':question:'
is_section = true
