# Pages after is_section = true is indented

[[pages]]
path = "main.py"
name = "Home"
icon = 'house-fill'
is_section = true

[[pages]]
name = "My Page"
icon = 'person-circle'
is_section = true

[[pages]]
path = "pages/performance.py"
name = "Performance"

[[pages]]
path = "pages/info.py"
name = "Info"

[[pages]]
path = "pages/admin.py"
name = "Admin"

[[pages]]
name = "Math Drill"
icon = 'trophy-fill'
is_section = true

[[pages]]
path = "pages/menu.py"
name = "Menu"

[[pages]]
path = "pages/practice.py"
name = "Question"

[[pages]]
path = "pages/graded.py"
name = "Graded result"

[[pages]]
path = "pages/chatbot.py"
name = "Chat with AI"
icon = 'person-plus-fill'
is_section = true
